CI: github action run with postgres

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -45,9 +45,8 @@ jobs:
         run: composer install --no-progress --prefer-dist --optimize-autoloader
       - name: Run Migration
         run: |
-          composer require --dev symfony/orm-pack
           php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
-          php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+          php bin/console doctrine:migrations:migrate --no-interaction || echo "No migrations found or migration failed"
         env:
           DATABASE_URL: postgres://postgres:postgres@127.0.0.1:${{ job.services.postgres.ports[5432] }}/postgres?charset=UTF-8
       - name: Install PHPUnit
