CI: now we just use phpunit

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -27,7 +27,6 @@ jobs:
         uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
         with:
           php-version: ${{ matrix.php-versions }}
-          tools: phpunit-bridge
           extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pgsql
           coverage: none #xdebug #optional
       - name: Get composer cache directory
@@ -45,13 +44,11 @@ jobs:
         run: composer install --no-progress --prefer-dist --optimize-autoloader
       - name: Run Migration
         run: |
-          php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
-          php bin/console doctrine:migrations:migrate --no-interaction || echo "No migrations found or migration failed"
+          php bin/console --env=test doctrine:schema:update --force || echo "No migrations found or schema update failed"
+          php bin/console --env=test doctrine:migrations:migrate --no-interaction || echo "No migrations found or migration failed"
         env:
           DATABASE_URL: postgres://postgres:postgres@127.0.0.1:${{ job.services.postgres.ports[5432] }}/postgres?charset=UTF-8
-      - name: Install PHPUnit
-        run: simple-phpunit install
       - name: Run tests
-        run: simple-phpunit --coverage-text
+        run: ./vendor/bin/phpunit --coverage-text
       - name: Run PhpStan
         run: phpstan analyse -l 4 src
