CI: github action run with postgres

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,51 +1,58 @@
-name: Continuous Integration
-
+# https://github.com/shivammathur/setup-php/blob/master/examples/symfony-postgres.yml
+# GitHub Action for Symfony with PostgreSQL
+name: Testing with PostgreSQL
 on: [push, pull_request]
-
-defaults:
-  run:
-    shell: bash
-
 jobs:
-  tests:
+  symfony:
+    name: Symfony (PHP ${{ matrix.php-versions }})
     runs-on: ubuntu-latest
-
+    services:
+      postgres:
+        image: postgres:10.8
+        env:
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: postgres
+          POSTGRES_DB: postgres
+        ports:
+          - 5432/tcp
+        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
     strategy:
+      fail-fast: false
       matrix:
-        php: [ '8.0' ]
-
+        php-versions: ['8.0']
     steps:
       - name: Checkout
         uses: actions/checkout@v2
-
-#      - name: Install system dependencies
-#        run: |
-#          echo "::group::apt-get update"
-#          sudo apt-get update
-#          echo "::endgroup::"
-
-      - name: Setup PHP
-        uses: shivammathur/setup-php@v2
+      - name: Setup PHP, with composer and extensions
+        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
         with:
-          coverage: "none"
-          extensions: ctype, iconv, intl, json, xsl, sqlite3, pgsql, xml, mbstring
-          ini-values: date.timezone=Europe/Paris,memory_limit=-1,default_socket_timeout=10,session.gc_probability=0,apc.enable_cli=1
-          php-version: "${{ matrix.php }}"
-          tools: composer:v2, phpstan
-
-#      - name: Display versions
-#        run: |
-#          php -r 'foreach (get_loaded_extensions() as $extension) echo $extension . " " . phpversion($extension) . PHP_EOL;'
-#          php -i
-
-      - name: "Install dependencies with composer"
-        run: composer install --no-interaction --no-progress --no-suggest --optimize-autoloader
-
-      - name: Run phpstan analyse src
-        run: phpstan analyse -l 4 src
-
-      - name: Run phpstan analyse tests
-        run: phpstan analyse -l 4 tests
-
+          php-version: ${{ matrix.php-versions }}
+          tools: phpunit-bridge
+          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pgsql
+          coverage: none #xdebug #optional
+      - name: Get composer cache directory
+        id: composer-cache
+        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
+      - name: Cache composer dependencies
+        uses: actions/cache@v2
+        with:
+          path: ${{ steps.composer-cache.outputs.dir }}
+          # Use composer.json for key, if composer.lock is not committed.
+          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
+          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
+          restore-keys: ${{ runner.os }}-composer-
+      - name: Install Composer dependencies
+        run: composer install --no-progress --prefer-dist --optimize-autoloader
+      - name: Run Migration
+        run: |
+          composer require --dev symfony/orm-pack
+          php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
+          php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+        env:
+          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:${{ job.services.postgres.ports[5432] }}/postgres?charset=UTF-8
+      - name: Install PHPUnit
+        run: simple-phpunit install
       - name: Run tests
-        run: make tests
+        run: simple-phpunit --coverage-text
+      - name: Run PhpStan
+        run: phpstan analyse -l 4 src
